# Generated by Django 5.2.3 on 2025-06-19 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('canceled', 'Отменено')], default='new', max_length=20)),
                ('service', models.CharField(choices=[('general', 'Генеральная уборка'), ('clean', 'Общий клининг'), ('himch', 'Химчистка ковров и мебели'), ('poslestr', 'Послестроительная уборка')], default='general', max_length=20)),
                ('payment', models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные')], default='card', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
